name: Pipeline
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
      - name: Install dependencies 🔧
        run: npm ci
      - name: Run lint
        run: npm run lint    
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
      - name: Install dependencies 🔧
        run: npm ci
      - name: Cache MongoDB binaries 📦
        uses: actions/cache@v4
        with:
          path: ~/.cache/mongodb-binaries
          key: mongodb-binaries-${{ runner.os }}-7.0.14
      - name: Run tests
        run: npm run test